### ISSUE TITLE
Suggestion: Having items last forever

### ISSUE THREAD

**Issue by MostFunGuy** [Mirreski/RandomSK#1]
Either an trigger to check when an item despawns, or have an expression for setting a delay, like the pickup delay :D :gem: (Or both of course)

**Comment by MostFunGuy** [comment]
Sorry if I screw something up... I'm not super used to GitHub, It wont let me label it?

**Comment by Mirreski** [comment]
Item Despawn event has been added already:) http://www.mirre.eu.pn/events/#ItemDespawn

Cancelling the item despawn event and extending the pick up delay of the item about to despawn will make an unpickupable and non despawning item. 

You can specify what the name and type of the item should be in the event so it will not happen for every item.

If find a simpler way i will add it like a expression i will add:)

**Comment by Mirreski** [comment]
Don't worry i am not super used to github either:P And my web browser doesn't seem to like github either, posted like 5 comments when i wanted to post one and closed/reopned accidently.
