### ISSUE TITLE
[Enhancement] Simple Expression: unix time

### ISSUE THREAD

**Issue by Matmorcat** [Mirreski/RandomSK#15]
Often times when you need to store a data in a database, it is best to store a time stamp of the current time (in unix format) for easy referencing. Unix time is simple and fast to use to get and store the time of an event down to the second.

For example if I want to get information from MySQL (using skQuery's SQL effect) for the past 24 hours, I could simply use something like 

```
SELECT * FROM sk_players WHERE `time-stamp`='%unix time-86400%'
```

without **unix time** I don't know of any simple way (less than 20 lines) to replicate this. **unix time** makes it really simple to get time where the actual date/time of day is not so important (relative time).

It's not too complex of an expression. It just returns a number value which corresponds to the number of seconds that have passed since the equinox (January 1st, 1970).

**Comment by Mirreski** [comment]
I don't have any idea where I can find a method for this but I can atleast look a little.

**Comment by Matmorcat** [comment]
I know very little about java, but this might help:
http://stackoverflow.com/questions/732034/getting-unixtime-in-java

```
long unixTime = System.currentTimeMillis() / 1000L;
```

**Comment by Mirreski** [comment]
Yea that was what I found when I googled, I probably won't release a new version soon, I am gonna work on some other stuff before i release another versiion. If you wan't prerelease pm me and I will send you it when I have added the expression(which will be soon since it is so simple).

**Comment by Mirreski** [comment]
Added in the latest version.
