### ISSUE TITLE
What am I working on right now?

### ISSUE THREAD

**Issue by Mirreski** [Mirreski/RandomSK#16]
Currently I am doing this:
- Remaking a lot, cleaning up shit.
- Remaking the sleep and wake up effects, Leave bed button will work.

Done Stuff:
- Expression for making players ignore collisions with entities(Players can't push entities if true)(Only 1.8 currently).
- Condition for checking if a player is in combat. (MC 1.8)

Future possible things I might work on:
- Alphabetical sorting.
- ItemStack Nbt (10% done).
- Replacement for SkQ's Particles for 1.8+
- Json in Books (not supported in Spigot 1.8 yet):(
- More NBT
- A command XDDD.

**Comment by RealGatt** [comment]
ItemStack Nbt (10% done).
Would love that to be done <3<3

**Comment by Mirreski** [comment]
Haha it is really annoying to work on NBT. 

I have managed some new stuff about a week ago.

set {_data} to compound of tool of player
set compound "display" inner string "Name" of {_data} to "Hello"
set compound "secret" inner string "Secrets" of {_data} to "FunnyGatt"
set tool of player to tool of player with compound {_data}

set {_s} to compound "secret" inner string "Secrets" of compound of tool of player
broadcast "Secrets: %{_s}%" #Broadcasts "Secrets: FunnyGatt"

But that was early attempts and I have am gonna change the syntax to something like below(probably) as the above syntax wasn't really good and probably limited. And I gotta find another way to apply the tags rather than just setting the tool.

set tag "display.Name" of {_compound} as string type to "Hello"
set string tag "secret.Secrets" of {_compound} to "FunnyGatt"
%nbttype% tag %string% of %compound%

The main problem is attributes(and enchants) as they are added in a different way than just setting the tag.

**Comment by RealGatt** [comment]
<3<3
