### ISSUE TITLE
Chest Animations?

### ISSUE THREAD

**Issue by Mirreski** [Mirreski/RandomSK#4]
Making a Chest open or closed without a player rightclicking. Attemping.

**Comment by Mirreski** [comment]
Done coming next version.

**Comment by MostFunGuy** [comment]
Chests work perfectly looks like, enderchest re-close after about 4 seconds automatically

**Comment by Mirreski** [comment]
Okay:), Didn't really test enderchests before releasing. However i am uncertain if i can make the enderchest not close after 4 seconds.
